Added code to handle accusations
Scranton-Sleuths/scranton-sleuths pull request #35
Opened 2024-04-12 22:57 UTC by kcavicchio

2024-04-12 23:40 UTC, EthanChe approved these changes
lgtm!

2024-04-12 23:44 UTC, EthanChe requested changes

2024-04-12 23:44 UTC, EthanChe commented on src/game/Player.js
> +      this.isActive = true;
If we want this variable to be part of the state, its type needs to be defined.

2024-04-13 00:53 UTC, zlmcdaniel approved these changes
Looks good!

2024-04-13 00:53 UTC, EthanChe approved these changes
lgtm

2024-04-13 00:55 UTC, merged